Numpy
- 


!pip install numpy --> syntax

In [2]:
#importing numpy
import numpy as np

In [4]:
#creating numpy
a = np.array([1,2,3])  #1D
b = np.array([[3,5,6], [35,3,2]])  #2D
c = np.array([[[6,3,5], [4,5,3], [6,3,5]],
              [[6,3,5], [4,5,3], [6,3,5]],
              [[6,43,5], [4,35,3], [4,5,3]]])  #3D


In [6]:
print(a)

[1 2 3]


In [8]:
print(b)

[[ 3  5  6]
 [35  3  2]]


In [10]:
print(c)

[[[ 6  3  5]
  [ 4  5  3]
  [ 6  3  5]]

 [[ 6  3  5]
  [ 4  5  3]
  [ 6  3  5]]

 [[ 6 43  5]
  [ 4 35  3]
  [ 4  5  3]]]


In [12]:
d = np.array([[[[3,5,6], [35,3,2], [3,5,3]]],
              [[[2,6,7], [5,4,3], [12,54,6]]],
              [[[9,5,6], [3,7,6], [8,34,6]]]])

In [14]:
print(d)

[[[[ 3  5  6]
   [35  3  2]
   [ 3  5  3]]]


 [[[ 2  6  7]
   [ 5  4  3]
   [12 54  6]]]


 [[[ 9  5  6]
   [ 3  7  6]
   [ 8 34  6]]]]


In [18]:
#create an array of zeros
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
#create an array of evenly spaced values(number of samples)

np.linspace(1, 15, 20)

array([ 1.        ,  1.73684211,  2.47368421,  3.21052632,  3.94736842,
        4.68421053,  5.42105263,  6.15789474,  6.89473684,  7.63157895,
        8.36842105,  9.10526316,  9.84210526, 10.57894737, 11.31578947,
       12.05263158, 12.78947368, 13.52631579, 14.26315789, 15.        ])

In [30]:
#create an array of ones

np.ones((1,5,3))  #shape,row,col

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Reshaping



In [49]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])

print(arr.size)

newarr = arr.reshape(1,13)
print(newarr)

13
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13]]


In [59]:
#convert 1-D array into 3-D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)
newarr = arr.reshape(1,4,3)
print(newarr)

12
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [63]:
#convert 1-D array into 2-D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)
newarr = arr.reshape(2,6)
print(newarr)

12
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [76]:
#convert 1-D array into 4-D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)
newarr = arr.reshape(2,1,3,2)
print(newarr)

12
[[[[ 1  2]
   [ 3  4]
   [ 5  6]]]


 [[[ 7  8]
   [ 9 10]
   [11 12]]]]


In [100]:
#convert 1-D array into 5-D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)
newarr = arr.reshape(1,1,6,1,2)
print(newarr)

12
[[[[[ 1  2]]

   [[ 3  4]]

   [[ 5  6]]

   [[ 7  8]]

   [[ 9 10]]

   [[11 12]]]]]


In [104]:
#convert 2-D array into 1-D array
arr = ([[3,5,6], [35,3,2]])
print(arr)


[[3, 5, 6], [35, 3, 2]]
